language: csharp
solution: Rauthor.sln
mono: none
dotnet: 3.1
cache:
  directories:
  - $HOME/.nuget/packages
script:
 - dotnet restore
 - dotnet build ./Rauthor.sln -f netcoreapp3.1
 - dotnet test --no-build Rauthor.UnitTests/Rauthor.UnitTests.csproj --filter Category!=DatabaseTest /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master