language: csharp
solution: Seterator.sln
mono: none
dotnet: 2.2
os: linux 
arch: arm64 
dist: xenial
services:
 - mysql
before_install:
 - sudo apt-get -y install powershell
 - sudo apt-get -y install sshpass
script:
 - dotnet restore
 - dotnet build ./Seterator.sln -f netcoreapp2.2
 - dotnet ef database update
 - dotnet test --no-build Seterator.UnitTests/Seterator.UnitTests.csproj --filter Category!=DatabaseTest /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
