language: csharp
solution: Seterator.sln
mono: none
dotnet: 3.1
services:
 - mysql
before_install:
 - sudo apt-get -y install powershell
 - sudo apt-get -y install sshpass
 - dotnet tool install --global dotnet-ef
script:
 - dotnet restore ./Seterator/Seterator.csproj
 - dotnet restore ./Seterator.UnitTests/Seterator.UnitTests.csproj
 - dotnet build ./Seterator/Seterator.csproj -f netcoreapp3.1 --no-restore
 - dotnet build ./Seterator.UnitTests/Seterator.UnitTests.csproj -f netcoreapp3.1 --no-restore
#- dotnet ef database update --project ./Seterator/Seterator.csproj
 - dotnet test --no-build Seterator.UnitTests/Seterator.UnitTests.csproj --filter Category!=DatabaseTest /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
