language: csharp
solution: Rauthor.sln
mono: none
dotnet: 2.2
script:
 - dotnet restore
 - dotnet build ./Rauthor.sln -f netcoreapp2.2
 - dotnet test --no-build Rauthor.UnitTests/Rauthor.UnitTests.csproj --filter Category!=DatabaseTest /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master