language: csharp
solution: Seterator.sln
mono: none
dotnet: 2.2
script:
 - dotnet restore
 - dotnet build ./Seterator.sln -f netcoreapp2.2
 - dotnet test --no-build Seterator.UnitTests/Seterator.UnitTests.csproj --filter Category!=DatabaseTest /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
