name: Server-side

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Save built project
      uses: actions/upload-artifact@v1
      with:
        name: built-project
        path: .
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Load built project
      uses: actions/download-artifact@v1
      with:
        name: built-project
    - name: Test
      run: dotnet test --no-build --verbosity normal built-project/Seterator.sln
